### ISSUE TITLE
an issue about x = layer(x)

### ISSUE THREAD

**Issue by jalamao** [utkuozbulak/pytorch-cnn-visualizations#1]
In cnn_layer_visualization.py, I find that x don't be used. How to understand x?

**Comment by utkuozbulak** [comment]
In Pytorch you can do a full forward pass from input to the output of the last layer with:
 
```
output = model(input)
```
But you can also do a forward pass layer by layer with:
```
x = input
for layer in model:
    x = layer(x)
```
Here, in every iteration x becomes the output from a previous layer.

Going back to the context, in layer visualization we hook the layer we want to visualize with forward hook. While doing a forward pass if that layer is passed then hook function returns the result(grad_out) of the selected layer. x there is not used because I just used it to trigger the forward hook function while doing a forward pass.

----

But, thinking about it again, you can also use x instead of *self.conv_output*. Because technically, the code breaks right after the selected layer so x is the output of that specific conv layer (a tensor of 1x512x28x28 for layer 17). So if you pick a filter like: 

`
x[0, self.selected_filter]
`

that will be equal to the variable *self.conv_output*

I was really into hook functions while coding this whole thing and turns out was kind of blind to see a simpler approach. I will include a version that does not use hooks for this task and comment the one that uses hooks to avoid further confusion. 

I hope that clears things a bit.

**Comment by utkuozbulak** [comment]
Updated the code to include a version without hooks and commented a bit more on the one that uses hooks [here](https://github.com/utkuozbulak/pytorch-cnn-visualizations/blob/master/src/cnn_layer_visualization.py).

**Comment by jalamao** [comment]
Thanks. I finally figure out what the hook is.
