### ISSUE TITLE
How should I start? :)

### ISSUE THREAD

**Issue by isalirezag** [utkuozbulak/pytorch-cnn-visualizations#13]
Hey
Sorry for the stupid question, but can you please tell how  i should start using this code?
What should i run if i wanna start ...
Can I give an input image and generates the maps?

Thanks

**Comment by utkuozbulak** [comment]
Hello, each operation is separate python file. Initially, it takes one of the samples as an input. You just run it, if you want to change the input image, just feed the image you want to the operation. The same for the model, you can just feed your model instead of pretrained ones. (Although the code makes certain assumptions for that, have a look at README)
