### ISSUE TITLE
Question about using features

### ISSUE THREAD

**Issue by himat** [utkuozbulak/pytorch-cnn-visualizations#46]
In the code from `update_relus` in guided_backprop.py, why do you only add hooks for the RELUs in `model.features` - what about `model.classifier`?
```  
        # Loop through layers, hook up ReLUs
        for pos, module in self.model.features._modules.items():
            if isinstance(module, ReLU):
                module.register_backward_hook(relu_backward_hook_function)
                module.register_forward_hook(relu_forward_hook_function)
```

**Comment by utkuozbulak** [comment]
Hey,

Sorry for the late reply, I believe it is like that because I had the impression from the paper that only the signals at feature level (convs) are imputed (See Fig1 from the paper). But quickly skimming the paper again, I fear you might be right about the activations at the classifier. I will have a detailed look when I have time.

**Comment by utkuozbulak** [comment]
Oh, now I remember. Because the guided grad was proposed in all-conv paper which only has conv layers, I decided to modify the relus at features (i.e., conv side) and not classifier (i.e., linear side). You can change it and see how it performs if all relus are modified.

You can read the original paper and [0] for more details.

[0]: https://towardsdatascience.com/iclr-2015-striving-for-simplicity-the-all-convolutional-net-with-interactive-code-manual-b4976e206760
