### ISSUE TITLE
visualize model that not in the model zoo

### ISSUE THREAD

**Issue by visonpon** [utkuozbulak/pytorch-cnn-visualizations#8]
HI! as you said:  

> If you want to port this code to use it on your model that does not have such separation, you just need to do some editing on parts where it calls model.features and model.classifier.

 I try to modify the model.features or .classifier part , but i get confused how to do it. Below is part of my script , hope that you can give some details about how to visualize own trained model.
```
model =torch.load(model_save_path)
for index,(layer,_) in enumerate(model.items()):
      # model.items() return the weight of this layer, eg, model.items()[0]=model.0.1.weight
      x = layer(x)
        ......
```
but i get the TypeError that the object is not callable. i wonder how to read the layer from the trained model that didn't have features attribute. thanks~

**Comment by utkuozbulak** [comment]
Hey, it doesn't have to contain features, what is important is for the model to contain nn.Sequential so that you can iterate.

Let me elaborate.

You can have an __ init __() function like this:

```
...
def __init__(self):
  self.layers = nn.Sequential(
    nn.Conv2d(1, 6, (5, 5), padding=2),
    nn.Conv2d(1, 6, (5, 5), padding=2),
    nn.Conv2d(1, 6, (5, 5), padding=2),
    .
    .
    .
 )

def forward(self, input):
  output = self.layers(input)
```

or this

```
...
def __init__(self):
    self.layer1 = nn.Conv2d(1, 6, (5, 5), padding=2),
    self.layer2 = nn.Conv2d(1, 6, (5, 5), padding=2),
    self.layer3 = nn.Conv2d(1, 6, (5, 5), padding=2),
    .
    .
    .
 
def forward(self, x):
  x = self.layer1(x)
  x = self.layer2(x)
  x = self.layer3(x)
  ...
```


If you have a model that wraps up layers with nn.Sequential then iterating through layers one by one is super easy.

```
x = input
for single_layer in model.layers():
   x = single_layer(x)
```

If there is no nn.Sequential wrapping it up, you can use .modules(), .named_children().

Have a look at these: 
https://discuss.pytorch.org/t/module-children-vs-module-modules/4551
https://discuss.pytorch.org/t/how-to-loop-over-all-the-variable-in-a-nn-module/912

Hope it helps.

**Comment by Raunak13** [comment]
Hi @visonpon , @utkuozbulak , I am getting the same errors. Can you tell me what did you do? 
While using model.getnamedchildren() the function 'get_output_from_specific_layer' returns values for first few layers, but then it gives the error: "RuntimeError: Given groups=1, weight[48, 192, 1, 1], so expected input[1, 64, 105, 105] to have 192 channels, but got 64 channels instead"
I am using Inception Resnet V3

**Comment by utkuozbulak** [comment]
I'm also getting some emails about how hard the whole procedure becomes when the model has nested elements (like Resnets). I might just make a ResNet example soon.

**Comment by himat** [comment]
Has a ResNet example been made?

**Comment by Saharkakavand** [comment]
@utkuozbulak  did you make that example about resnet?

**Comment by utkuozbulak** [comment]
I had one done for one of my projects but did not put it in this repository.

Adapting the code to resnet, or for any other architecture that has nested blocks, is not hard. You only need to change two or three lines of code where it hooks the layers. Because resnet has residual blocks, what you want is to hook the layers inside these blocks and not the blocks themselves.
